title: Berty Assets
baseURL: https://assets.berty.tech

params:
  category_order: ['logo_official', 'animation', 'logo_variations', 'various_usage', 'icons']

  # Map mimetype to placeholder icons
  nonimage_icons:
    plain: images/icon_txt.svg
    vnd.adobe.photoshop: images/icon_psd.svg
    postscript: images/icon_ai.svg
    zip: images/icon_zip.svg

  # Show only assets with below mimetypes
  shown_assets:
    - "jpg"
    - "jpeg"
    - "png"
    - "gif"
    - "svg+xml"
    - "plain"
    - "vnd.adobe.photoshop"
    - "postscript"
    - "zip"

relativeURLs: true