[build]
publish = "public"
command = "npm run pre-build && hugo --gc --minify"
ignore = "(exit 1)"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = 'npm run pre-build && hugo --gc --minify -b $DEPLOY_PRIME_URL --enableGitInfo'

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[context.branch-deploy]
command = 'npm run pre-build && hugo --gc --minify -b $DEPLOY_PRIME_URL --enableGitInfo'

[context.branch-deploy.environment]
HUGO_VERSION = "0.69.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  