[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = 'npm run build -b $DEPLOY_PRIME_URL --enableGitInfo'

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.0"

[context.branch-deploy]
command = 'npm run build -b $DEPLOY_PRIME_URL --enableGitInfo'

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
